spring:
  application:
    name: my-app
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/micro_order?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password:
server:
  port: 8080
